name: Build Typst document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        
      - name: Install fontist
        uses: fontist/setup-fontist@v2
      - name: Installs fonts
        run: fontist install 'Arial' --accept_all_licenses
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.11.0
        
      - name: Compile Document
        run: typst compile --font-path ~/.fontist/fonts smyth_resume.typ smyth_resume.pdf
        
      - name: Upload artifact
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: smyth_resume.pdf
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Latest
          files: smyth_resume.pdf
